version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: chmod 755 gradlew
      - run:
          name: Clean project
          command: ./gradlew clean
      - run:
          name: Assemble project
          command: ./gradlew assemble
      - run:
          name: Tests
          command: ./gradlew test
      run:
        name: test
        command: echo $TEST_VARIABLE
